apiVersion: v1
kind: Pod
metadata:
  name: bastion
  namespace: bastion
spec:
  hostNetwork: true
  containers:
  - name: secrets
    image: ${kmsctl_image}
    args:
    - --region=${aws_region}
    - get
    - --output-dir=/root/.ssh/
    - --bucket=${secrets_bucket_name}
    - --sync=true
    - --sync-interval=3m
    - --recursive=true
    - authorized_keys
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 800Mi
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
    - name: root
      mountPath: /root
  volumes:
  - name: secrets
    emptyDir: {}
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: root
    hostPath:
      path: /root
