#cloud-config

coreos:
  update:
    reboot-strategy: 'off'
  units:
  - name: systemd-sysctl.service
    command: restart
  - name: fleet.service
    enable: false
  - name: etcd2.service
    enable: false
    command: stop
  - name: update-engine.service
    command: stop
    enable: false
  - name: format-docker-volume.service
    command: start
    content: |
      [Unit]
      Description=Formats the docker volume
      After=dev-xvdd.device
      Requires=dev-xvdd.device
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/bash -c '/usr/sbin/blkid /dev/xvdd || (/usr/sbin/wipefs -f /dev/xvdd && /usr/sbin/mkfs.ext4 /dev/xvdd)'
  - name: var-lib-docker.mount
    command: start
    enable: true
    content: |
      [Unit]
      Description=Mount docker volume
      Requires=format-docker-volume.service
      After=format-docker-volume.service
      Before=docker.service
      [Mount]
      What=/dev/xvdd
      Where=/var/lib/docker
      Type=ext4
  - name: docker.service
    drop-ins:
    - name: 10-opts.conf
      content: |
        [Service]
        Environment="DOCKER_OPTS=--iptables=false --log-opt max-size=100m --log-opt max-file=1 --default-ulimit=nofile=32768:32768 --default-ulimit=nproc=16384:16384"
  - name: kubelet.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Kubelet
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes

      [Service]
      Restart=always
      RestartSec=10
      RuntimeDirectory=kubelet
      RuntimeDirectoryMode=0700
      Environment=KUBELET_IMAGE_TAG={{ .kubernetes_version }}
      Environment=KUBELET_IMAGE_URL={{ .kubernetes_image }}
      EnvironmentFile=/etc/kmsctl
      EnvironmentFile=/etc/environment
      EnvironmentFile=/etc/aws-environment
      Environment="RKT_RUN_ARGS=--volume dns,kind=host,source=/etc/resolv.conf \
        --mount volume=dns,target=/etc/resolv.conf \
        --mount volume=etc-ssl-certs,target=/etc/ssl/certs \
        --mount volume=stage,target=/tmp \
        --mount volume=var-lib-rkt,target=/var/lib/rkt \
        --mount volume=var-log,target=/var/log \
        --volume stage,kind=host,source=/tmp \
        --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
        --volume var-log,kind=host,source=/var/log \
        --volume etc-ssl-certs,kind=host,source=/etc/ssl/certs"

      ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
      ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --address=0.0.0.0 \
        --allow-privileged=true \
        --cpu-cfs-quota=true \
        --host-network-sources=* \
        --hostname-override=${COREOS_PRIVATE_IPV4} \
        --image-gc-high-threshold=60 \
        --image-gc-low-threshold=40 \
        --logtostderr=true \
        --maximum-dead-containers-per-container=1 \
        --maximum-dead-containers=10 \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --system-reserved=cpu=50m,memory=100Mi
write_files:
- path: /etc/kmsctl
  content: |
    AWS_S3_BUCKET={{ .secrets_bucket_name }}
    AWS_DEFAULT_REGION={{ .aws_region }}
- path: /etc/aws-environment
  content: |
    AWS_REGION={{ .aws_region }}
    DNS_ZONE_NAME={{ .private_zone_name }}
    ENVIRONMENT={{ .environment }}
- path: /etc/kubernetes/manifests/kube-manifests.yml
  permissions: 0444
  owner: root
  content: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: kube-manifests
      namespace: kube-system
    spec:
      hostNetwork: true
      containers:
      - name: manifests
        image: {{ .kmsctl_image }}
        args:
        - --region={{ .aws_region }}
        - get
        - --output-dir=/etc/kubernetes/manifests
        - --bucket={{ .secrets_bucket_name }}
        - --sync=true
        - --recursive=true
        - manifests/bastion
        volumeMounts:
        - name: manifests
          mountPath: /etc/kubernetes/manifests
      volumes:
      - name: manifests
        hostPath:
          path: /etc/kubernetes/manifests
- path: /var/lib/iptables/rules-save
  content: |
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    -A FORWARD -d 169.254.169.254/32 -i docker0 -p tcp -m tcp -j DROP
    -A FORWARD -i docker0 -p tcp -m tcp --dport 2379 -j DROP
    :OUTPUT ACCEPT [0:0]
    COMMIT

- path: /etc/sysctl.d/10-disable-ipv6.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6 = 1
